config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :twets do
    member do
      post 'like'
    end
  end
  root 'twets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :twet
  validates_uniqueness_of :user_id, scope: :twet_id
end

app/models/twet.rb
class Twet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy

    # Add a method to increment the likes count
    def increment_likes_count
      self.increment!(:likes_count)
    end
  
    # Add a method to decrement the likes count
    def decrement_likes_count
      self.decrement!(:likes_count)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :twets,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation,:current_password)
    end

end

app/controllers/twets_controller.rb
class TwetsController < ApplicationController
  before_action :set_twet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_twet, only: [:show, :like]


  # GET /twets or /twets.json
  def index
    @twets = Twet.all.order('created_at DESC')
    @twet = Twet.new
  end
  
  def like
    # Check if the user has already liked this Twet
    if @twet.likes.exists?(user_id: current_user.id)
      flash[:alert] = "You've already liked this Twet."
    else
      # Create a new like only if the user hasn't liked it before
      @twet.likes.create(user_id: current_user.id)
      @twet.increment_likes_count
      flash[:notice] = "You've liked this Twet."
    end

    redirect_to root_path
  end

  # GET /twets/1 or /twets/1.json
  def show
    redirect_to root_path
  end

  # GET /twets/new
  def new
    @twet = current_user.twets.build
  end

  # GET /twets/1/edit
  def edit
  end

  # POST /twets or /twets.json
  def create
    @twet = current_user.twets.build(twet_params)

    respond_to do |format|
      if @twet.save
        format.html { redirect_to twet_url(@twet), notice: "Twet was successfully created." }
        format.json { render :show, status: :created, location: @twet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twets/1 or /twets/1.json
  def update
    respond_to do |format|
      if @twet.update(twet_params)
        format.html { redirect_to twet_url(@twet), notice: "Twet was successfully updated." }
        format.json { render :show, status: :ok, location: @twet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twets/1 or /twets/1.json
  def destroy
    @twet.destroy

    respond_to do |format|
      format.html { redirect_to twets_url, notice: "Twet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twet
      @twet = Twet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twet_params
      params.require(:twet).permit(:twet,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twets_helper.rb
module TwetsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def fetch_first_n_users(n)
        User.limit(n)
    end

end

app/views/layouts/_navbar.html.erb
<!-- app/views/layouts/_navbar.html.erb -->

<nav class="navbar navbar-expand-lg navbar-info bg-info">
  <div class="container">
    <!-- Navbar Brand (Left) -->
    <%= link_to 'Tweet', root_path,class: "navbar-brand text-white" %>

    <!-- Navbar Toggler (for responsive design) -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar Buttons (Right) -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
      <% if user_signed_in? %>
          <div class="dropdown">
            <a class="btn btn-outline-success text-white dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             <%= current_user.username %>
            </a>

            <ul class="dropdown-menu" >
              <li><%= link_to 'Edit Profile', edit_user_registration_path	, class:'dropdown-item' %></li>
              <li><%= link_to 'Logout', destroy_user_session_path	, class:'dropdown-item', method: :delete %></li>
            </ul>
        </div>
      <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:'btn btn-outline-success text-white' %>      
          </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/twets/_feed.html.erb
<div class="row g-2">
    <div class="col-sm-3">
        <div class="card mb-3">
            <div class="row no-gutters">
                <!-- Circular Image (Left) -->
                <% if user_signed_in? %>
                    <div class="col-md-4">
                        <div
                            class="rounded-circle overflow-hidden"
                            style="width: 100px; height: 100px;">
                            <%= gravatar_image_tag(current_user.email,size: 64, alt: current_user.name) %>
                        </div>
                    </div>
                    <!-- Card Content (Right) -->
                    <div class="col-md-8">
                        <div class="card-body">
                            <!-- Name (Bold) -->
                            <h5 class="card-title font-weight-bold"><%= current_user.name %></h5>
                            <!-- Username -->
                            <p class="card-text">
                                @<%= current_user.name %>
                            </p>
                            <!-- Text -->
                            <p class="card-text">Total Tweets: <%= current_user.twets.all.count %></p>
                        </div>
                    </div>
                <% else %>
                    <h3 class='px-3 text-center py-5'> 
                        Please Sign in to Share Content.
                    
                        <%= link_to 'Sign-In', user_session_path, class:'btn btn-outline-primary mt-3' %>      
                    </h3>
                <% end %>
                
            </div>
        </div>
    </div>
    <div class="col-sm-6">
     <% if flash[:alert] %>
            <div class="alert alert-danger">
                <%= flash[:alert] %>
                </div>
                <% elsif flash[:notice] %>
                <div class="alert alert-success">
                <%= flash[:notice] %>
            </div>
    <% end %>
        <% if user_signed_in? %>
            <%= render 'form' %>
        <% end %>
        <% @twets.each do |twet| %>
            <div class="card mb-3">
                <div class="row no-gutters">
                    <!-- Circular Image (Left) -->
                    <div class="col-md-2">
                    <div class="rounded-circle overflow-hidden mt-3 ms-1" style="width: 64px; height: 64px;">
                        <!-- Placeholder Image URL -->
                        <%= gravatar_image_tag(twet.user.email,size: 64, alt: twet.user.name) %>
                    </div>
                    </div>
                    <!-- Card Content (Right) -->
                    <div class="col-md-10">
                            <div class="card-body">
                                <!-- Name (Bold) -->
                                <h5 class="card-title font-weight-bold"><%= twet.user.name %></h5>
                                <!-- Username -->
                                <p class="card-text">@<%= twet.user.name %></p>
                                <!-- Text -->
                                <p class="card-text"><%= twet.twet %></p>
                                 <% if user_signed_in? && twet.user.name != current_user.name %>
                                    <div class="row">
                                        <div class="col">
                                            <%= link_to like_twet_path(twet), method: :post, class: 'like-link' do %>
                                                <span class="btn btn-outline-success"><%= twet.likes_count %> Like</span>
                                            <% end %>
                                        </div>
                                    </div>
                                 <% end %>
                                 
                                <% if user_signed_in? && twet.user.name == current_user.name %>
                                    <div class="row">
                                        <div class="col">
                                            <%= link_to 'Edit', edit_twet_path(twet), class:'btn btn-outline-warning' %>
                                            <%= link_to 'Delete', twet_path(twet), method: :delete, class:'btn btn-outline-danger' %> 
                                            <%= link_to like_twet_path(twet), method: :post, class: 'like-link' do %>
                                            <span class="btn btn-outline-success"><%= twet.likes_count %> Like</span>
                                            <% end %>
                                        </div>
                                    </div>  
                                <% end %>
                                    
                            </div>
                        
                    </div>
                </div>
            </div>
        <% end %>
        
    </div>
    <div class="col-sm-3">
        <h5 class='text-center'>Other Users</h5>
         <hr />

         <%# calling function from helper method %>

         <% users = fetch_first_n_users(5) %>
         <% users.each do |user| %>
          <% if user_signed_in? && user.name == current_user.name %>
                                <% next %>
          <% else %>
            <div class="card mb-3">
                <div class="row no-gutters">
                    <!-- Circular Image (Left) -->
                    <div class="col-md-4">
                        <div
                            class="rounded-circle overflow-hidden mt-3 ms-1"
                            style="width: 64px; height: 64px;">
                            <%= gravatar_image_tag(user.email,size: 64, alt: user.name) %>
                        </div>
                    </div>
                    <!-- Card Content (Right) -->
                    <div class="col-md-8">
                        <div class="card-body">
                            <!-- Name (Bold) -->
                           
                            <h5 class="card-title font-weight-bold"><%= user.username %></h5>
                            <!-- Username -->
                            <p class="card-text">@<%= user.name %></p>
                            
                        </div>
                    </div>
                </div>
            </div>

            
          <% end %>          
         <% end %>
            
    </div>
</div>

app/views/twets/_form.html.erb
<%= form_for(@twet) do |form| %>
        <% if @twet.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(twet.errors.count, "error") %> prohibited this twet from being saved:</h2>

            <ul>
              <% @twet.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="card mb-3 border shadow">
            <div class="row no-gutters">
                <!-- Circular Image (Left) -->
                <div class="col-md-2">
                    <div
                        class="rounded-circle overflow-hidden mt-3 ms-1"
                        style="width: 100px; height: 100px;">
                        <%= gravatar_image_tag(current_user.email,size: 100, alt: current_user.name) %>
                    </div>
                </div>
                <!-- Card Content (Right) -->
                <div class="col-md-10">
                    <div class="card-body">
                        <%= form.text_area :twet , class:'form-control', rows:5 %>
                        <div class="actions mt-2">
                            <%= form.submit 'Create Tweet' ,class:'btn btn-primary' %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<% end %>

app/views/twets/edit.html.erb
<h1>Editing Twet</h1>

<%= render 'form', twet: @twet %>

<%= link_to 'Show', @twet %> |
<%= link_to 'Back', twets_path %>

app/views/twets/index.html.erb
<div class="container mt-5">
  <%= render './twets/feed' %>
</div>

app/views/twets/new.html.erb
<h1>New Twet</h1>

<%= render 'form', twet: @twet %>

<%= link_to 'Back', twets_path %>

app/views/twets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Twet:</strong>
  <%= @twet.twet %>
</p>

<%= link_to 'Edit', edit_twet_path(@twet) %> |
<%= link_to 'Back', twets_path %>